[package]
name = "zkp_basicos"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "sumando_n"
function = "zkp_basicos::sum_n::sumando_n"
sierra = true
casm = true

[dependencies]
starknet = "2.11.2"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
